### ISSUE TITLE
Maybe a BUG

### ISSUE THREAD

**Issue by ComputerMystery** [carpedm20/DCGAN-tensorflow#104]
In the model.py seems exits a bug.This part below returns a float for reshape but reshape just accept int32. seems need to convert

`def conv_out_size_same(size, stride): return math.ceil(float(size) / float(stride))`

@carpedm20

**Comment by carpedm20** [comment]
This is fixed. Thanks for report

**Comment by ani16** [comment]
Hi

After resolving this issue, it is still not testing. I have trained on my own dataset. Why it is not taking while testing?
