### ISSUE TITLE
scipy.misc.imresize is deprecated in scipy 1.0.0, and removed in 1.3.0

### ISSUE THREAD

**Issue by WasabiThumb** [carpedm20/DCGAN-tensorflow#351]
DCGAN attempts to use method scipy.misc.imresize, I had to uninstall scipy and install scipy==1.2.2

In this version, the method still works but is deprecated. [Scipy docs suggest using Pillow instead](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imresize.html).

**Comment by WasabiThumb** [comment]
I've fixed the issue and created a PR- as seen https://github.com/carpedm20/DCGAN-tensorflow/compare/master...WasabiThumb:patch-1

**Comment by FireFox1616** [comment]
@WasabiThumb does it work for you? Because i had to do some little correction and still can't use it, becase of the error "TypeError: data type not understood".

Correction done:
`  im = Image.fromarray(x[j:j+crop_h, i:i+crop_w].astype('uint8'))
`

**Comment by WasabiThumb** [comment]
> @WasabiThumb does it work for you? Because i had to do some little correction and still can't use it, becase of the error "TypeError: data type not understood".
> 
> Correction done:
> ` im = Image.fromarray(x[j:j+crop_h, i:i+crop_w].astype('uint8'))`

It works if you do it this way:
'im = np.array(Image.fromarray(x[j:j+crop_h, i:i+crop_w]).resize([resize_h, resize_w]), PIL.Image.BILINEAR)'

**Comment by yz3007** [comment]
check the codes that you change below:
'np.array(im.resize([resize_h, resize_w]), PIL.Image.BILINEAR)' is absoutely wrong. you should put BILINEAR inside of im.resize 

In addtion, 
 im = Image.fromarray(image[j:j+crop_h, i:i+crop_w])
where are variable i and variable j?

You made a lot of typos and mistakes in the 'transform' function so that I have to check older version of this repo.


def transform(image, input_height, input_width, 
              resize_height=64, resize_width=64, crop=True):
  if crop:
    cropped_image = center_crop(
      image, input_height, input_width, 
      resize_height, resize_width)
  else:
    im = Image.fromarray(image[j:j+crop_h, i:i+crop_w])
  return np.array(im.resize([resize_h, resize_w]), PIL.Image.BILINEAR)/127.5 - 1.
